<?php
declare(strict_types=1);
require_once __DIR__.'/includes/auth.php';
require_once __DIR__.'/includes/clubs.php';
require_role(['donor','seeker','admin']);
require_once __DIR__.'/includes/address.php';
$pdo=db();$user=current_user();$id=(int)($_GET['id']??0);$errors=[];
if($_SERVER['REQUEST_METHOD']==='POST') {
    verify_csrf();
    try { $updated=club_action($pdo,$user,$_POST);flash('success','Club workflow updated.');redirect('clubs.php?id='.$updated); }
    catch(Throwable $e) { $errors[]=safe_error($e); }
}
$admin=$user['role']==='admin';
$club=$id?bb_one($pdo,'SELECT * FROM clubs WHERE id=?',[$id]):null;
if($id && (!$club || ($club['status']!=='Approved' && !$admin && (int)$club['coordinator_id']!==(int)$user['id']))) { http_response_code(404);exit('Club not available.'); }
$manage=$club && ($admin || (int)$club['coordinator_id']===(int)$user['id']);
$clubs=bb_all($pdo,$admin?'SELECT * FROM clubs ORDER BY id DESC':"SELECT * FROM clubs WHERE status='Approved' OR coordinator_id=? ORDER BY id DESC",$admin?[]:[$user['id']]);
$hospitals=bb_all($pdo,"SELECT id,name FROM hospitals WHERE status='Verified' ORDER BY name");
$pageTitle='University clubs';require __DIR__.'/includes/header.php';
function club_hidden(int $id):void { echo '<input type="hidden" name="csrf_token" value="'.e(csrf_token()).'"><input type="hidden" name="club_id" value="'.$id.'">'; }
?>
<section class="page-heading"><div><h1><?= $club?e($club['name']):'University clubs' ?></h1><p>Clubs coordinate donors and campaigns. Only authorized hospital staff perform clinical screening.</p></div><a class="button button-secondary" href="clubs.php">All Clubs</a></section>
<?php form_errors($errors); ?>
<?php if(!$club): ?>
<section class="content-card"><h2>Club directory</h2><?php foreach($clubs as $c): ?><article class="review-card"><div><a href="clubs.php?id=<?= (int)$c['id'] ?>"><strong><?= e($c['name']) ?></strong></a><span><?= e($c['university']) ?> · <?= e($c['location']) ?></span><small><?= e($c['status']) ?></small></div></article><?php endforeach; ?><?php if(!$clubs): ?><p>No clubs yet.</p><?php endif; ?></section>
<?php if(in_array($user['role'],['donor','seeker'],true)): ?><section class="content-card form-card top-gap"><h2>Register your club</h2><form method="post" class="form-grid"><?php club_hidden(0); ?><input type="hidden" name="action" value="create"><label><span>Club name</span><input name="name" maxlength="160" required></label><label><span>University</span><input name="university" maxlength="160" required></label><?php render_address_picker(); ?><label><span>University approval / verification reference</span><input name="reference" maxlength="160" required></label><div class="form-wide"><button class="button button-primary">Apply as Coordinator</button></div></form></section><?php endif; ?>
<?php else:
$membership=bb_one($pdo,'SELECT status FROM club_members WHERE club_id=? AND user_id=?',[$id,$user['id']]);
$counts=bb_one($pdo,"SELECT COUNT(*) AS n FROM club_members WHERE club_id=? AND status='Approved'",[$id]);
$donations=bb_one($pdo,"SELECT COUNT(*) AS n FROM direct_donations WHERE club_id=? AND status='Completed'",[$id]);
?>
<section class="content-card"><h2><?= e($club['university']) ?></h2><p><?= e($club['location']) ?> · <?= e($club['status']) ?> · <?= (int)$counts['n'] ?> members · <?= (int)$donations['n'] ?> hospital-confirmed club donations</p>
<?php if($manage): ?><p>Reference: <?= e($club['reference']) ?> · Review: <?= e($club['review_note']) ?></p><?php endif; ?>
<?php if(!$membership && in_array($user['role'],['donor','seeker'],true)): ?><form method="post"><?php club_hidden($id); ?><label class="checkbox-label"><input type="checkbox" name="consent" required><span>I agree to share my name and blood group with this club's coordinator and receive club notifications</span></label><button class="button button-primary" name="action" value="join">Request to Join</button></form><?php elseif($membership): ?><p>Your membership: <?= e($membership['status']) ?></p><?php if((int)$club['coordinator_id']!==(int)$user['id']): ?><form method="post"><?php club_hidden($id); ?><button class="button button-secondary" name="action" value="leave">Leave Club / Withdraw</button></form><?php endif; ?><?php endif; ?></section>
<?php if($admin): ?><section class="content-card form-card top-gap"><h2>Club verification</h2><form method="post" class="form-grid"><?php club_hidden($id); ?><input type="hidden" name="action" value="review"><label><span>Decision</span><select name="status"><option>Approved</option><option>Rejected</option><option>Suspended</option></select></label><label class="form-wide"><span>Verification / rejection reason</span><textarea name="review_note" maxlength="500" required></textarea></label><button class="button button-primary">Save Decision</button></form></section><?php endif; ?>
<?php if($manage): $members=bb_all($pdo,'SELECT m.*,u.full_name,u.blood_group FROM club_members m JOIN users u ON u.id=m.user_id WHERE club_id=?',[$id]); ?>
<section class="content-card top-gap"><h2>Member requests</h2><?php foreach($members as $m): ?><article class="review-card"><div><strong><?= e($m['full_name']) ?></strong><small><?= e($m['blood_group']) ?> · <?= e($m['status']) ?></small></div><?php if((int)$m['user_id']!==(int)$club['coordinator_id']): ?><form method="post"><?php club_hidden($id); ?><input type="hidden" name="action" value="member"><input type="hidden" name="member_id" value="<?= (int)$m['user_id'] ?>"><button class="button button-primary" name="status" value="Approved">Approve</button> <button class="button button-secondary" name="status" value="Rejected">Reject / Remove</button></form><?php endif; ?></article><?php endforeach; ?></section>
<section class="content-card form-card top-gap"><h2>Coordinate a blood request</h2><p>Only reviewed, pending donor requests can be shared. No prescription, patient note or phone number is shared with the club.</p><form method="post" class="form-grid"><?php club_hidden($id); ?><input type="hidden" name="action" value="share"><label><span>Request ID</span><input type="number" name="request_id" min="1" required></label><button class="button button-primary">Notify Matching Members</button></form>
<?php $available=bb_all($pdo,"SELECT id,blood_group,location FROM blood_requests WHERE status='Pending' AND source_type='Donor' AND prescription_status='Reviewed' AND expires_at>NOW() ORDER BY id DESC LIMIT 20"); foreach($available as $r): ?><p>#<?= (int)$r['id'] ?> · <?= e($r['blood_group']) ?> · <?= e($r['location']) ?></p><?php endforeach; ?></section>
<section class="content-card form-card top-gap"><h2>Create a campaign</h2><form method="post" class="form-grid"><?php club_hidden($id); ?><input type="hidden" name="action" value="campaign"><label><span>Title</span><input name="title" maxlength="160" required></label><?php render_address_picker(); ?><label><span>Date and time</span><input type="datetime-local" name="event_at" required></label><label><span>Clinical partner hospital</span><select name="hospital_id"><?php foreach($hospitals as $h): ?><option value="<?= (int)$h['id'] ?>"><?= e($h['name']) ?></option><?php endforeach; ?></select></label><button class="button button-primary">Create Campaign</button></form></section>
<?php endif; ?>
<section class="content-card top-gap"><h2>Campaigns</h2><?php $events=bb_all($pdo,'SELECT c.*,h.name AS hospital_name,(SELECT COUNT(*) FROM campaign_registrations r WHERE r.campaign_id=c.id) AS registrations FROM campaigns c JOIN hospitals h ON h.id=c.hospital_id WHERE club_id=? ORDER BY event_at DESC',[$id]); foreach($events as $event): $signed=bb_one($pdo,'SELECT user_id FROM campaign_registrations WHERE campaign_id=? AND user_id=?',[$event['id'],$user['id']]); ?><article class="review-card"><div><strong><?= e($event['title']) ?></strong><span><?= e($event['event_at']) ?> · <?= e($event['location']) ?></span><small><?= e($event['hospital_name']) ?> · <?= e($event['status']) ?> · <?= (int)$event['registrations'] ?> registrations</small></div><form method="post"><?php club_hidden($id); ?><input type="hidden" name="campaign_id" value="<?= (int)$event['id'] ?>"><?php if($signed): ?><button class="button button-secondary" name="action" value="unrsvp">Withdraw Registration</button><?php elseif($event['status']==='Scheduled'): ?><button class="button button-primary" name="action" value="rsvp">Register</button><?php endif; ?></form>
<?php if($manage && $event['status']==='Scheduled'): ?><form method="post"><?php club_hidden($id); ?><input type="hidden" name="action" value="campaign_status"><input type="hidden" name="campaign_id" value="<?= (int)$event['id'] ?>"><button class="button button-secondary" name="status" value="Cancelled">Cancel Event</button> <button class="button button-secondary" name="status" value="Completed">Mark Event Completed</button></form><?php endif; ?></article><?php endforeach; ?><?php if(!$events): ?><p>No campaigns yet.</p><?php endif; ?><p class="muted">Event registration/completion does not mark anyone as a donor or increase inventory. Hospital donation confirmation is required.</p></section>
<?php endif; ?>
<?php require __DIR__.'/includes/footer.php'; ?>
