import fs from 'node:fs';
import assert from 'node:assert/strict';
import {JSDOM} from 'jsdom';
const root=new URL('../',import.meta.url).pathname.replace(/\/$/,'');
const results=[];
const check=(name,run)=>{try{run();results.push({test:name,status:'PASS'});}catch(e){results.push({test:name,status:'FAIL',detail:e.message});}};
const picker='<fieldset data-address-picker><select data-address-division><option value="">All</option><option>Dhaka</option><option>Rangpur</option></select><select data-address-district><option value="">All</option></select><select data-address-upazila><option value="">All</option></select><script type="application/json" data-address-data>{"Dhaka":{"Dhaka":["Savar","Dhanmondi"]},"Rangpur":{"Kurigram":["Kurigram Sadar"]}}</script></fieldset>';
const dom=new JSDOM(picker+picker,{runScripts:'outside-only'});
dom.window.eval(fs.readFileSync(root+'/assets/js/address.js','utf8'));
const fields=dom.window.document.querySelectorAll('[data-address-picker]');
const [division,district,area]=fields[0].querySelectorAll('select');
const change=(el,value)=>{el.value=value;el.dispatchEvent(new dom.window.Event('change'));};
check('Division populates only its districts',()=>{change(division,'Dhaka');assert.deepEqual(Array.from(district.options,o=>o.value),['','Dhaka']);});
check('District populates its areas',()=>{change(district,'Dhaka');assert.deepEqual(Array.from(area.options,o=>o.value),['','Savar','Dhanmondi']);});
check('Changing division removes old district and area',()=>{change(area,'Savar');change(division,'Rangpur');assert.equal(district.value,'');assert.equal(area.value,'');assert.equal(area.options.length,1);});
check('Separate form pickers do not change each other',()=>assert.equal(fields[1].querySelector('[data-address-district]').options.length,1));
check('Cleared division clears dependent options',()=>{change(division,'');assert.equal(district.options.length,1);assert.equal(area.options.length,1);});
const mapDom=new JSDOM('<fieldset data-map-picker><button data-locate></button><button data-map-clear></button><div data-map-canvas></div><p data-map-message></p><input name="latitude"><input name="longitude"></fieldset>',{runScripts:'outside-only'});
let gpsCalls=0;
Object.defineProperty(mapDom.window.navigator,'geolocation',{value:{getCurrentPosition(ok,fail){gpsCalls++;fail();}}});
mapDom.window.eval(fs.readFileSync(root+'/assets/js/maps.js','utf8'));
const doc=mapDom.window.document;
check('No automatic geolocation request',()=>assert.equal(gpsCalls,0));
check('Missing map library leaves manual coordinate input usable',()=>{doc.querySelector('[name=latitude]').value='23.8';doc.querySelector('[name=longitude]').value='90.4';doc.querySelector('[name=longitude]').dispatchEvent(new mapDom.window.Event('change'));assert.equal(doc.querySelector('[name=latitude]').value,'23.8000000');});
check('Clear pin clears both coordinates',()=>{doc.querySelector('[data-map-clear]').click();assert.equal(doc.querySelector('[name=latitude]').value,'');assert.equal(doc.querySelector('[name=longitude]').value,'');});
check('Denied GPS gives actionable fallback',()=>{doc.querySelector('[data-locate]').click();assert.equal(gpsCalls,1);assert.match(doc.querySelector('[data-map-message]').textContent,/denied or unavailable/);});
console.log(JSON.stringify(results,null,2));
if(results.some(r=>r.status==='FAIL'))process.exitCode=1;
